#!/bin/bash
#PBS -l nodes=1:ppn=20
#PBS -l walltime=01:00:00
#PBS -N lab2_1
#PBS -o lab2_1.out
#PBS -e lab2_1.err
#PBS -q workq
#PBS -A loni_cyen405
#PBS -m e
#PBS -M lrc035@latech.edu

work="/home/lrc035/labTwo/labTwoSubmission"
XFILE="lab2_1"

cd $work
./$XFILE
