#!/bin/bash
#PBS -l nodes=1:ppn=20
#PBS -l walltime=01:00:00
#PBS -N lab2_4
#PBS -o lab2_4.out
#PBS -e lab2_4.err
#PBS -q workq
#PBS -A loni_cyen405
#PBS -m e
#PBS -M lrc035@latech.edu

work="/home/lrc035/labTwo/labTwoSubmission"
XFILE="lab2_4"

cd $work

echo "MPI run with 4 processes"
mpirun -np 4 -machinefile $PBS_NODEFILE ./$XFILE
echo "MPI run with 8 processes"
mpirun -np 8 -machinefile $PBS_NODEFILE ./$XFILE
